plugins:
  manual_trigger:
    enabled: true
  timer:
    enabled: false
    every_seconds: 30
  gpu_vram:
    enabled: true
    every_seconds: 3
    gpu_index: 0
    change_threshold_pct: 2.0
    alert_threshold_pct: 75.0
  rules_basic:
    enabled: true
  console_debug:
    enabled: true
  steelseries_oled:
    enabled: true
    target: primary_surface
